logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:INFO}
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver




management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=false
#
#management.endpoint.health.show-details=never
#
#logging.level.org.springframework.security=WARN
#logging.level.com.tms.tm_auth_service=INFO
#
#JWT_SECRET=${JWT_SECRET}
