#logging
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#DB connection
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:authdb}
spring.datasource.username=${DATABASE_USERNAME:rinugeorge}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver