spring.application.name=${SPRING_APP_NAME:tm-auth-service}
server.port=${PORT:8080}


# refresh token config
security.jwt.refresh-token-expiration-days=${REFRESH_TOKEN_EXPIRATION_DAYS:7}


#logging
logging.pattern.console= ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

#spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
#
jwt.secret=${JWT_SECRET}

#
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false











